### ISSUE TITLE
incorrect dependency type

### ISSUE THREAD

**Issue by chorny** [kablamo/p5-chef-knife-cmd#2]
Minilla is listed as 'build' dependency in cpanfile. If it is not used in module installation, it should be listed as 'develop'. See https://metacpan.org/pod/CPAN::Meta::Spec#Phases

**Comment by kablamo** [comment]
I know.  You are right.  I have just been lazy to do that.  Thanks for creating an issue though.  This does need to get fixed.

**Comment by kablamo** [comment]
Fixed. Pushed.  Released.
